### ISSUE TITLE
pycomplete==0.3.1 fails to build due to invalid pyproject.toml

### ISSUE THREAD

**Issue by dtrodrigues** [frostming/pycomplete#5]
When running `pip install --no-binary :all: pycomplete==0.3.1`, it fails due to pdm not finding a `project` section in the `pyproject.toml`:

```
#  pip install --no-binary :all: pycomplete==0.3.1
Collecting pycomplete==0.3.1
  Downloading pycomplete-0.3.1.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp9irzz09f
         cwd: /tmp/pip-install-98nsfzk2/pycomplete_11b6d2ce9c5a47eaa52971e042fae911
    Complete output (25 lines):
    Traceback (most recent call last):
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 58, in __init__
        self._metadata = self._read_pyproject(self.filepath)
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 65, in _read_pyproject
        return data["project"]
    KeyError: 'project'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/api.py", line 29, in prepare_metadata_for_build_wheel
        dist_info = Path(metadata_directory, builder.dist_info_name)
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/wheel.py", line 104, in dist_info_name
        name = to_filename(self.meta.project_name)
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/base.py", line 119, in meta
        self._meta = Metadata(self.location / "pyproject.toml")
      File "/tmp/pip-build-env-05xf7dm2/overlay/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 60, in __init__
        raise ProjectError("The project's pyproject.toml is not valid.")
    pdm.pep517.metadata.ProjectError: The project's pyproject.toml is not valid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp9irzz09f Check the logs for full command output.
```

**Comment by frostming** [comment]
@dtrodrigues  Thanks for the report. I have updated the build backend, would you please rerun the build?

**Comment by dtrodrigues** [comment]
Yep that fixed it. Thanks!
